/* Generated By:JavaCC: Do not edit this line. JoSQLParserConstants.java */
package org.josql.parser;

public interface JoSQLParserConstants {

  int EOF = 0;
  int K_AS = 5;
  int K_BY = 6;
  int K_IS = 7;
  int K_IN = 8;
  int K_OR = 9;
  int K_ON = 10;
  int K_ALL = 11;
  int K_AND = 12;
  int K_NOT = 13;
  int K_ASC = 14;
  int K_DESC = 15;
  int K_NULL = 16;
  int K_LIKE = 17;
  int K_INLIKE = 18;
  int K_FROM = 19;
  int K_WHERE = 20;
  int K_GROUP = 21;
  int K_LIMIT = 22;
  int K_ORDER = 23;
  int K_SELECT = 24;
  int K_HAVING = 25;
  int K_BETWEEN = 26;
  int K_DISTINCT = 27;
  int K_USE = 28;
  int K_TRUE = 29;
  int K_FALSE = 30;
  int K_EXECUTE = 31;
  int K_RESULTS = 32;
  int K_WHERE_RESULTS = 33;
  int K_HAVING_RESULTS = 34;
  int K_GROUP_BY_RESULTS = 35;
  int K_NEW = 36;
  int K_INTO = 37;
  int S_IDENTIFIER = 38;
  int LETTER = 39;
  int SPECIAL_CHARS = 40;
  int S_CHAR_LITERAL = 41;
  int S_CHAR_LITERAL2 = 42;
  int S_DOUBLE = 43;
  int S_INTEGER = 44;
  int DIGIT = 45;
  int LINE_COMMENT = 46;
  int MULTI_LINE_COMMENT = 47;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AS\"",
    "\"BY\"",
    "\"IS\"",
    "\"IN\"",
    "\"OR\"",
    "\"ON\"",
    "\"ALL\"",
    "\"AND\"",
    "\"NOT\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"INLIKE\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"GROUP\"",
    "\"LIMIT\"",
    "\"ORDER\"",
    "\"SELECT\"",
    "\"HAVING\"",
    "\"BETWEEN\"",
    "\"DISTINCT\"",
    "\"USE\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"EXECUTE\"",
    "\"RESULTS\"",
    "\"WHERE_RESULTS\"",
    "\"HAVING_RESULTS\"",
    "\"GROUP_BY_RESULTS\"",
    "\"new\"",
    "\"->\"",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_CHAR_LITERAL2>",
    "<S_DOUBLE>",
    "<S_INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\":\"",
    "\":_\"",
    "\"?\"",
    "\".\"",
    "\"@\"",
    "\";\"",
    "\",\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"$\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
  };

}
